### ISSUE TITLE
Question about the `2 × TPU-v4 Training` in the Technical Report

### ISSUE THREAD

**Issue by Orion-Zheng** [tanyuqian/redco#1]
Hi thank you very much for your work! 
The technical report mentioned that you train `T5-XXL-11B` and `OPT-13B` on `2 TPU-v4`.
<img width="1034" alt="image" src="https://github.com/tanyuqian/redco/assets/62330719/92b9ffd8-5cfb-4fd7-808d-c6244db84587">
I would like to know if the `2 TPU-v4` refer to two independent TPU-v4 VMs connected by VPC network, or a TPU-v4 Pod Slice(as shown below)?
<img width="738" alt="image" src="https://github.com/tanyuqian/redco/assets/62330719/25a8fd03-e8a0-4fcb-9b11-8cc1eff75106">
I am very curious about this because I have access to 5 TPU v3-8 VMs obtained from the TRC program. I wanted to use all these 5 VMs to train a single model, but I could not find an appropriate way to make it work. I know in the TPU Pod, TPUs are connected by dedicated high-speed network so the distributed training can be very fast. But I don't know if it is possible to make multiple TPU VMs work together by connect them to a VPC network. 
Any information will be really appreciated!

**Comment by tanyuqian** [comment]
Thanks a lot for niticing RedCoast!

The TPUs in our test are TPU Pods, i.e., `2 x TPU-v4` -> `2x2x2`, `16 x TPU-v4` -> `4x4x4`. Thanks for the question, we will articulate this in the next version of our report.

Though we don't test TPU VMs (cuz we don't have such resource), `redco.Deployer` supports multi-host setting on separate machines as long as they can access each other via IPs (without platforms like SLURM, Xmanager, etc.). This is described [here in the language model example](https://github.com/tanyuqian/redco/tree/redco-v0.4.15/examples/language_modeling#general-case) (by filling in [these 5 arguments](https://github.com/tanyuqian/redco/blob/redco-v0.4.15/redco/deployers/deployer.py#L44-L48) appropriately). 

Regarding how to connect multiple TPU VMs, we also don't have experience on VPC network. Sorry for not being able to provide a complete solution to your case.
